CREATE TABLE  IF NOT EXISTS ITEMS(
ID NUMBER(10) NOT NULL,
TYPE VARCHAR(50) NOT NULL,
PRODUCT VARCHAR(100) NOT NULL,
COST DECIMAL NOT NULL
);

CREATE TABLE  IF NOT EXISTS USER(
ID NUMBER(10) NOT NULL,
NAME VARCHAR(100) NOT NULL,
IS_AFFLIATED_INDICATOR BIT DEFAULT FALSE,
IS_EMPLOYEE_INDICATOR BIT DEFAULT FALSE,
DATE TIMESTAMP
);


