INSERT INTO ITEMS (ID, TYPE,PRODUCT,COST) VALUES (1, 'grocery','vegetables',100);
INSERT INTO ITEMS (ID, TYPE,PRODUCT,COST) VALUES (2, 'grocery','fruits',200);
INSERT INTO ITEMS (ID, TYPE,PRODUCT,COST) VALUES (3, 'others','furniture',400);
INSERT INTO ITEMS (ID, TYPE,PRODUCT,COST) VALUES (4, 'others','clothes',300);

INSERT INTO USER (ID, NAME,IS_AFFLIATED_INDICATOR,IS_EMPLOYEE_INDICATOR,DATE) VALUES (1, 'ashok',0,1,parsedatetime('17-09-2012 18:47:52.690', 'dd-MM-yyyy hh:mm:ss.SS'));
INSERT INTO USER (ID, NAME,IS_AFFLIATED_INDICATOR,IS_EMPLOYEE_INDICATOR,DATE) VALUES (2, 'abhishek',1,0,parsedatetime('17-09-2013 18:47:52.690', 'dd-MM-yyyy hh:mm:ss.SS'));
INSERT INTO USER (ID, NAME,IS_AFFLIATED_INDICATOR,IS_EMPLOYEE_INDICATOR,DATE) VALUES (3, 'rubin',0,0,parsedatetime('17-09-2014 18:47:52.690', 'dd-MM-yyyy hh:mm:ss.SS'));
INSERT INTO USER (ID, NAME,IS_AFFLIATED_INDICATOR,IS_EMPLOYEE_INDICATOR,DATE) VALUES (4, 'sumeet',0,0,parsedatetime('17-09-2015 18:47:52.690', 'dd-MM-yyyy hh:mm:ss.SS'));
INSERT INTO USER (ID, NAME,IS_AFFLIATED_INDICATOR,IS_EMPLOYEE_INDICATOR,DATE) VALUES (5, 'rohit',0,0,parsedatetime('17-09-2013 18:47:52.690', 'dd-MM-yyyy hh:mm:ss.SS'));

